# Generated by Django 5.2.8 on 2025-11-28 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assunto',
            options={'ordering': ['materia', 'titulo']},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='assunto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assunto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('ADMIN', 'Administrador')], default='ALUNO', max_length=20),
        ),
    ]
