# Generated by Django 5.2.8 on 2025-11-28 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_assunto_options_alter_materia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assunto',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assuntos', to='main.materia'),
        ),
    ]
